-
  branches:
    only:
      - master
      
  configuration: release
  
  deploy:
    - provider: NuGet
      api_key:
        secure: uPuXKM0rxdT6dpMSsTT/2EzISr7Xm6Fe/n5Oz7JCpV2YUbSu/tkU9IV63DDVmMfb
      on:
        APPVEYOR_REPO_TAG_NAME: ReleaseToNuGet
        APPVEYOR_REPO_TAG: true
        
  
-
  configuration: debug
  
version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: normal
deploy:
